
server:
  port: 1111
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahadevgade/MS_Security_Properties
          clone-on-start: true
          
          
management:
  endpoints:
    web:
      exposure:
        include: '*'